/**
 * Shared driving code for the end-to-end suite. Not a spec file: Playwright collects `*.spec.js`.
 *
 * ## How a test plays a turn
 *
 * Two controls since issue #31: pick one of the three drawn dice cards, then click a pawn twice. A
 * test plays by doing those and by waiting for the board's own attributes, never by sleeping.
 * `data-phase` and `data-status` were added to the DOM contract for precisely this.
 *
 * **The card the tests pick is always the one in slot 0.** Not because it is the best card, but
 * because `scripts/find-seeds.js` replays with `hand[0]`, and slot 0 holds `hand[0]`. Picking any
 * other slot would make every seed below wrong, and the point of that script is that the two policies
 * are the same one written twice.
 *
 * ## Why every spec passes a seed
 *
 * `?seed=N` fixes the RNG (NFR-09), so the same URL plays the same match every time. The seeds below
 * were not guessed and they are not maintained by hand either: `npm run test:seeds` replays matches
 * headlessly with the same policy these helpers use, always activating the lowest-numbered pawn that
 * can move, and prints this block. That is what makes "seed 9 captures on turn 8" a fact rather than
 * a hope.
 *
 * **Re-run that script whenever something changes what the RNG is spent on.** It has happened three
 * times already:
 *
 * 1. Issue #30 replaced the single stand-in die with the twenty-card pool, so the pool began drawing
 *    from the same generator the die rolls from.
 * 2. Issue #38's skill squares draw from it again, to decide where a used-up square reappears.
 * 3. Issue #38's skill cards draw from it twice more: 57 times to shuffle the pool when the match
 *    starts, and once at the start of every turn.
 *
 * Every time, every previous seed played a different match from the same number. Every time the fix
 * was one command, which is the whole reason `scripts/find-seeds.js` was written down. The first two
 * seeds below survived all three changes by coincidence and the other three did not.
 *
 * `?fast=1` collapses **six** waits in the turn loop to zero: the pause after a move, the pause after a
 * refusal, the thirty-second reaction window (issue #38), the two-second hold on a trap a card fired
 * (issue #45), the roll's own 900 ms (D70), and the bot's thinking pause (issue #43). It changes the
 * waiting and nothing else: the same intents run in the same order, and a window still opens. A run
 * with `?fast=1` behaves as though every eligible player declined at once, which the rules already have.
 *
 * The count above said three while there were already four, so `src/options.js`'s `FAST_DELAYS` is the
 * list that cannot go stale. `roll-animation.spec.js` asks for `fast: false`, because the hold is its
 * subject, and two cases in `bots.spec.js` do the same for the same reason.
 */

import { expect } from "@playwright/test";

/**
 * Seeds chosen for what they produce, with the turn each situation first happens on.
 *
 * Generated by `npm run test:seeds` against both card pools and the full nine-step turn.
 */
export const SEEDS = {
  /** 4 players. A pawn leaves the start area on turn 1. */
  leavesStartAtOnce: { seed: 1, players: 4 },
  /**
   * 2 players. Leaves on turn 1 and, since issue #89's bonus roll, makes its first ordinary advance on
   * the second roll of that same turn 1 (it was turn 3 before).
   */
  advancesEarly: { seed: 1, players: 2 },
  /** 2 players. First capture on turn 4. Seed 83 until issue #89 re-timed every match. */
  capturesEarly: { seed: 166, players: 2 },
  /** 4 players. Turn 1 has no legal move at all, so the first thing on screen is a refusal. */
  passesOnTurnOne: { seed: 2, players: 4 },
  /** 2 players. Seat 2 fills its house and wins on turn 56. Seed 238 (seat 0, turn 77) until issue #89. */
  winsQuickest: { seed: 74, players: 2 },
};

/**
 * Open a match. `fast` is on unless a test explicitly wants the real pauses.
 *
 * `stack` is a list of skill card ids that becomes the top of the skill pool, so a spec can be sure the
 * hand it is about to play from holds the card it is testing. It arrives as `?stack=` and `src/main.js`
 * carries the reason a seed could not do the same job: `scripts/find-seeds.js` never plays a card, so it
 * cannot search for a seed whose shuffle deals a named one.
 */
export async function openMatch(page, { seed, players }, { fast = true, stack = null } = {}) {
  const query = [
    `?seed=${seed}`,
    `&players=${players}`,
    fast ? "&fast=1" : "",
    stack === null ? "" : `&stack=${stack.join(",")}`,
  ].join("");
  await page.goto(`/${query}`);

  const board = page.locator(".board");
  await expect(board).toHaveAttribute("data-players", String(players));
  return board;
}

/** The board's current phase, status, turn number, chosen die and roll, read in one go. */
export async function boardState(board) {
  return {
    phase: await board.getAttribute("data-phase"),
    status: await board.getAttribute("data-status"),
    activePlayer: Number(await board.getAttribute("data-active-player")),
    turnNumber: Number(await board.getAttribute("data-turn")),
    roll: Number(await board.getAttribute("data-roll")),
    die: Number(await board.getAttribute("data-die")),
    // Which roll of the turn this is (issue #89). A bonus roll is the same turn with this count up one.
    rolls: Number(await board.getAttribute("data-rolls")),
  };
}

/** Where every pawn stands, keyed `"seat.pawn"`. */
export async function pawnPositions(board) {
  return board
    .locator(".pawn")
    .evaluateAll((pawns) =>
      Object.fromEntries(
        pawns.map((pawn) => [
          `${pawn.getAttribute("data-player")}.${pawn.getAttribute("data-pawn")}`,
          Number(pawn.getAttribute("data-r")),
        ])
      )
    );
}

/** The lowest-numbered pawn that can move this turn. Always the same one, so a match is repeatable. */
export function firstMovablePawn(board) {
  return board.locator('.pawn[data-movable="true"]').first();
}

/**
 * The dice hand.
 *
 * Reached through `board.page()` rather than through the board, because design spec 03 put the hand
 * in a rail beside the board (D30) and not inside it.
 */
export function diceHand(board) {
  return board.page().locator(".hand--dice");
}

/**
 * The prompt strip, which is where the action phase and the reaction window ask their questions.
 *
 * Beside the board like the hands, for the same reason: it is not inside `.board`.
 */
export function prompt(board) {
  return board.page().locator(".prompt");
}

/**
 * The turn drivers live in `turn-helpers.js` since issue #89 and are re-exported from here, so no spec
 * had to change an import when this file crossed the 300-line limit. The seam is the one the two files'
 * headers describe: this file reads the board, that one plays it.
 */
export * from "./turn-helpers.js";
