/**
 * Shared driving code for the end-to-end suite. Not a spec file: Playwright collects `*.spec.js`.
 *
 * ## How a test plays a turn
 *
 * Two controls since issue #31: pick one of the three drawn dice cards, then click a pawn twice. A
 * test plays by doing those and by waiting for the board's own attributes, never by sleeping.
 * `data-phase` and `data-status` were added to the DOM contract for precisely this.
 *
 * **The card the tests pick is always the one in slot 0.** Not because it is the best card, but
 * because `scripts/find-seeds.js` replays with `hand[0]`, and slot 0 holds `hand[0]`. Picking any
 * other slot would make every seed below wrong, and the point of that script is that the two policies
 * are the same one written twice.
 *
 * ## Why every spec passes a seed
 *
 * `?seed=N` fixes the RNG (NFR-09), so the same URL plays the same match every time. The seeds below
 * were not guessed and they are not maintained by hand either: `npm run test:seeds` replays matches
 * headlessly with the same policy these helpers use, always activating the lowest-numbered pawn that
 * can move, and prints this block. That is what makes "seed 9 captures on turn 8" a fact rather than
 * a hope.
 *
 * **Re-run that script whenever something changes what the RNG is spent on.** It has happened three
 * times already:
 *
 * 1. Issue #30 replaced the single stand-in die with the twenty-card pool, so the pool began drawing
 *    from the same generator the die rolls from.
 * 2. Issue #38's skill squares draw from it again, to decide where a used-up square reappears.
 * 3. Issue #38's skill cards draw from it twice more: 57 times to shuffle the pool when the match
 *    starts, and once at the start of every turn.
 *
 * Every time, every previous seed played a different match from the same number. Every time the fix
 * was one command, which is the whole reason `scripts/find-seeds.js` was written down. The first two
 * seeds below survived all three changes by coincidence and the other three did not.
 *
 * `?fast=1` collapses **three** waits in the turn loop to zero: the pause after a move, the pause after
 * a refusal, and since issue #38 the thirty-second reaction window. It changes the waiting and nothing
 * else: the same intents run in the same order, and a window still opens. A run with `?fast=1` simply
 * behaves as though every eligible player declined at once, which is a situation the rules already have.
 */

import { expect } from "@playwright/test";

/**
 * Seeds chosen for what they produce, with the turn each situation first happens on.
 *
 * Generated by `npm run test:seeds` against both card pools and the full nine-step turn.
 */
export const SEEDS = {
  /** 4 players. A pawn leaves the start area on turn 1. */
  leavesStartAtOnce: { seed: 1, players: 4 },
  /** 2 players. Leaves on turn 1, first ordinary advance on turn 3. */
  advancesEarly: { seed: 1, players: 2 },
  /** 2 players. First capture on turn 4. */
  capturesEarly: { seed: 83, players: 2 },
  /** 4 players. Turn 1 has no legal move at all, so the first thing on screen is a refusal. */
  passesOnTurnOne: { seed: 2, players: 4 },
  /** 2 players. Seat 0 fills its house and wins on turn 77. */
  winsQuickest: { seed: 238, players: 2 },
};

/** Open a match. `fast` is on unless a test explicitly wants the real pauses. */
export async function openMatch(page, { seed, players }, { fast = true } = {}) {
  const query = `?seed=${seed}&players=${players}${fast ? "&fast=1" : ""}`;
  await page.goto(`/${query}`);

  const board = page.locator(".board");
  await expect(board).toHaveAttribute("data-players", String(players));
  return board;
}

/** The board's current phase, status, turn number, chosen die and roll, read in one go. */
export async function boardState(board) {
  return {
    phase: await board.getAttribute("data-phase"),
    status: await board.getAttribute("data-status"),
    activePlayer: Number(await board.getAttribute("data-active-player")),
    turnNumber: Number(await board.getAttribute("data-turn")),
    roll: Number(await board.getAttribute("data-roll")),
    die: Number(await board.getAttribute("data-die")),
  };
}

/** Where every pawn stands, keyed `"seat.pawn"`. */
export async function pawnPositions(board) {
  return board
    .locator(".pawn")
    .evaluateAll((pawns) =>
      Object.fromEntries(
        pawns.map((pawn) => [
          `${pawn.getAttribute("data-player")}.${pawn.getAttribute("data-pawn")}`,
          Number(pawn.getAttribute("data-r")),
        ])
      )
    );
}

/** The lowest-numbered pawn that can move this turn. Always the same one, so a match is repeatable. */
export function firstMovablePawn(board) {
  return board.locator('.pawn[data-movable="true"]').first();
}

/**
 * The dice hand.
 *
 * Reached through `board.page()` rather than through the board, because design spec 03 put the hand
 * in a rail beside the board (D30) and not inside it.
 */
export function diceHand(board) {
  return board.page().locator(".hand--dice");
}

/**
 * The prompt strip, which is where the action phase and the reaction window ask their questions.
 *
 * Beside the board like the hands, for the same reason: it is not inside `.board`.
 */
export function prompt(board) {
  return board.page().locator(".prompt");
}

/**
 * Pick the dice card in slot 0 and wait until choosing has actually happened.
 *
 * **Choosing no longer rolls.** Until issue #38 `choose-die` ran steps 3 to 5 as one intent; the action
 * phase now sits in that gap, so the phase after this is `action` when the player holds a playable card
 * and `act` or `turn-end` when they do not. `carryOn` below is the other half.
 *
 * **The wait cannot be "the phase is no longer `choose`", and that mistake cost half a test run.**
 * With `?fast=1` a turn nobody can move in rolls, passes, hands over and draws the next hand inside
 * one tick, so between the click and the next poll the board is back in `choose` for the *next*
 * player. The phase looks unchanged and the click looks lost. The turn number only counts upward, so
 * "the phase moved on, or the turn did" is the condition that cannot be fooled. This is the same trap
 * `waitPastTurn` below was written for.
 */
export async function chooseDiceCard(board) {
  const { turnNumber } = await boardState(board);

  await diceHand(board).locator('.card[data-slot="0"]').click();

  await expect
    .poll(
      async () => {
        const now = await boardState(board);
        return now.phase !== "choose" || now.turnNumber > turnNumber || now.status !== "running";
      },
      { timeout: 15_000 }
    )
    .toBe(true);
}

/**
 * Press "carry on" if the turn is waiting in the action phase, and do nothing if it is not.
 *
 * A no-op most of the time, which is the point: the loop skips the action phase by itself whenever the
 * active player holds no playable card, so a spec cannot know in advance whether the button will be
 * there. Asking the board rather than assuming is what keeps every spec that predates issue #38 working
 * with one extra line.
 *
 * **It plays no card.** These helpers drive the turn, and a card played here would change the RNG
 * sequence and invalidate every pinned seed. Playing cards is `skill-hand.spec.js`'s job.
 */
export async function carryOn(board) {
  const { phase, turnNumber } = await boardState(board);
  if (phase !== "action") return;

  await prompt(board).locator('[data-prompt-action="skip"]').click();

  await expect
    .poll(
      async () => {
        const now = await boardState(board);
        return now.phase !== "action" || now.turnNumber > turnNumber || now.status !== "running";
      },
      { timeout: 15_000 }
    )
    .toBe(true);
}

/**
 * Choose a dice card and then get past the action phase, which is what most specs actually want.
 *
 * Two steps where issue #31 had one. Kept as a pair rather than folded into `chooseDiceCard`, because a
 * spec that is *about* the action phase needs to stop between them.
 */
export async function chooseAndCarryOn(board) {
  await chooseDiceCard(board);
  await carryOn(board);
}

/**
 * Wait until the turn number has moved past `turnNumber`, or the match has ended.
 *
 * **Always wait on the turn number, never on the phase or the active seat.** With `?fast=1` a turn
 * nobody can move in passes itself in the same tick, so between two polls the board can leave `act`,
 * hand over, pass, hand back and be in `act` again. The phase and the seat would both read unchanged.
 * The turn number only counts upward, so it cannot hide a turn that has already happened.
 */
async function waitPastTurn(board, turnNumber) {
  await expect
    .poll(
      async () => {
        const now = await boardState(board);
        return now.status !== "running" || now.turnNumber > turnNumber;
      },
      { timeout: 15_000 }
    )
    .toBe(true);
}

/**
 * Move the lowest-numbered movable pawn.
 *
 * Two clicks on the same pawn, which is the interaction the game loop implements: the first selects
 * and the second commits. The pawn keeps `data-movable` in between, so the locator resolves to the
 * same element both times.
 */
export async function moveFirstMovablePawn(board) {
  const pawn = firstMovablePawn(board);

  await pawn.click();
  await expect(pawn).toHaveAttribute("data-selected", "true");
  await pawn.click();
}

/**
 * Play whatever this turn still needs, then wait for it to be over.
 *
 * Handles all three states the turn can be in when it is called: a card still to choose, a pawn ready
 * to move, or a turn already finished because nothing could move. A caller does not have to look at
 * the phase first, which is what stops every spec from having to know the shape of a turn.
 */
export async function playTurn(board) {
  const { turnNumber, phase } = await boardState(board);

  if (phase === "choose") await chooseDiceCard(board);
  await carryOn(board);
  if ((await boardState(board)).phase === "act") await moveFirstMovablePawn(board);

  await waitPastTurn(board, turnNumber);
}

/**
 * Play until `done(board)` returns true, or until the match ends, or until the step cap is reached.
 *
 * **`done` is asked once per step and not once per turn**, and the step that matters is the one after
 * a card has been chosen: at that point the roll is known and no pawn has moved yet, which is the only
 * moment a caller can ask "is this the situation I was waiting for" and still act on the answer. That
 * is why choosing does a `continue` rather than falling through to the pawn.
 *
 * The cap is a real bound and not a formality: a bug that parks the loop in one phase forever would
 * otherwise hang the suite instead of failing it. It counts steps, so a match may use two per turn.
 */
export async function playUntil(board, done, maxSteps = 400) {
  for (let step = 0; step < maxSteps; step += 1) {
    if (await done(board)) return true;

    const { status, phase, turnNumber } = await boardState(board);
    if (status !== "running") return await done(board);

    if (phase === "choose") {
      await chooseDiceCard(board);
      await carryOn(board);
      continue;
    }

    if (phase === "action") {
      await carryOn(board);
      continue;
    }

    if (phase === "act") await moveFirstMovablePawn(board);

    await waitPastTurn(board, turnNumber);
  }

  throw new Error(`the match did not reach the wanted situation within ${maxSteps} steps`);
}
